events {}

http {
    resolver 127.0.0.11 valid=30s ipv6=off;

    upstream auth_service {
        zone auth_service 64k;
        server auth-service:8001 resolve;
    }

    upstream user_service {
        zone user_service 64k;
        server user-service:8002 resolve;
    }

    upstream product_service {
        zone product_service 64k;
        server product-service:8003 resolve;
    }

    upstream order_service {
        zone order_service 64k;
        server order-service:8004 resolve;
    }

    upstream payment_service {
        zone payment_service 64k;
        server payment-service:8006 resolve;
    }

    upstream chat_service {
        zone chat_service 64k;
        server chat-service:8005 resolve;
    }

    server {
        listen 80;

        location /health {
            access_log off;
            return 200 "api-gateway healthy\n";
        }

        location /auth {
            rewrite ^/auth/?(.*)$ /$1 break;
            proxy_pass http://auth_service;
        }

        location /users {
            rewrite ^/users/?(.*)$ /$1 break;
            proxy_pass http://user_service;
        }

        location /products {
            rewrite ^/products/?(.*)$ /$1 break;
            proxy_pass http://product_service;
        }

        location /orders {
            rewrite ^/orders(.*)$ $1 break;
            proxy_pass http://order_service;
        }

        location /payment {
            rewrite ^/payment(.*)$ $1 break;
            proxy_pass http://payment_service;
        }

        location /chat {
            rewrite ^/chat(.*)$ $1 break;
            proxy_pass http://chat_service;
        }
    }
}
