events {}

http {
    upstream auth_service {
        server auth-service:8001;
    }

    upstream user_service {
        server user-service:8002;
    }

    upstream product_service {
        server product-service:8003;
    }

    upstream order_service {
        server order-service:8004;
    }

    upstream chat_service {
        server chat-service:8005;
    }

    server {
        listen 80;

        location /health {
            access_log off;
            return 200 "api-gateway healthy\n";
        }

        location /auth/ {
            rewrite ^/auth/(.*)$ /$1 break;
            proxy_pass http://auth_service;
        }

        location /users/ {
            rewrite ^/users/(.*)$ /$1 break;
            proxy_pass http://user_service;
        }

        location /products/ {
            rewrite ^/products/(.*)$ /$1 break;
            proxy_pass http://product_service;
        }

        location /orders/ {
            rewrite ^/orders/(.*)$ /$1 break;
            proxy_pass http://order_service;
        }

        location /chat/ {
            rewrite ^/chat/(.*)$ /$1 break;
            proxy_pass http://chat_service;
        }
    }
}
